import { defineConfig, devices } from "@playwright/test";

// Playwright config for bwipp-rs's web workbench.
//
// Run locally (assumes the production build has been generated by
// `npm run build` and is served by `npm start` on PORT 3000):
//
//   npm run test:e2e
//
// CI invokes the same script through `scripts/ci-web.sh`. GitHub
// Actions stays `workflow_dispatch`-only per project policy.

// Dedicated, non-default port so the e2e suite NEVER silently attaches
// to whatever a developer happens to be running on :3000 (the Next.js
// dev default). Combined with `reuseExistingServer: false`, Playwright
// always boots ITS OWN production server for the bwipp-rs workbench, so
// the suite can't pass/fail against a foreign app. Override the port
// with PLAYWRIGHT_PORT only if 3137 collides on your box.
const PORT = process.env.PLAYWRIGHT_PORT ?? "3137";
const BASE_URL = process.env.PLAYWRIGHT_BASE_URL ?? `http://127.0.0.1:${PORT}`;

export default defineConfig({
  testDir: "./tests",
  // Fail fast + loud if the served app isn't the bwipp-rs workbench
  // (e.g. someone pointed PLAYWRIGHT_BASE_URL at the wrong server).
  globalSetup: "./tests/global-setup.ts",
  // No retries — flake should be debugged at source, not papered over.
  retries: 0,
  // Single worker keeps the assertions deterministic since the Rust
  // WASM engine loads once per page and the catalog dropdown depends
  // on the same selectedId state across mode switches.
  workers: 1,
  reporter: "list",
  use: {
    baseURL: BASE_URL,
    trace: "off",
    // The page boots the WASM engine asynchronously; give it generous
    // headroom on a cold local CI invocation. Individual tests
    // can tighten this with `await expect(...).toBeVisible({ timeout })`.
    actionTimeout: 15_000,
    navigationTimeout: 30_000,
  },
  webServer: {
    // Bind the production server to the dedicated port explicitly.
    command: `npm start -- -p ${PORT}`,
    url: BASE_URL,
    // Never reuse a foreign server — always start our own, even locally.
    reuseExistingServer: false,
    timeout: 60_000,
  },
  projects: [
    {
      name: "desktop-chromium",
      use: { ...devices["Desktop Chrome"] },
    },
    {
      name: "mobile-chromium",
      use: { ...devices["Pixel 5"] },
    },
  ],
});
